# Generated by Django 5.2.15 on 2026-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionmodel',
            name='dossier_complet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptionmodel',
            name='exporte_proeco',
            field=models.BooleanField(default=False),
        ),
    ]
